---
# tasks file for kibana
  - name: Upload .tar.gz Upload Kibana file containing binaries from local storage
    copy:
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    register: get_kibana
    until: get_kibana is succeeded
    tags: kibana
  - name: Create directrory for Kibana
    file:
      state: directory
      path: "{{ kibana_home }}"
    tags: kibana
  - name: Install SUDO
    package:
      name: sudo
    tags: elastic
  - name: Extract Kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ kibana_home }}/bin/kibana"
    tags: kibana
  - name: Set environment Kibana
    become: true
    template:
      src: templates/kibana.sh.j2
      dest: /etc/profile.d/kibana.sh
    tags: kibana.sh.j2
